[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "RFL"
version = "1.0.3"
description = "Rackslab Foundation Library"

[tool.black]
target-version = ['py36']
color = 1

[tool.ruff]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = ["E", "F"]
target-version = "py37"

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = true
env_list = py{37,38,39,310,311,312}
skip_missing_interpreters = true

[testenv]
description = install pytest in a virtual environment and invoke it on the tests folder
deps =
  pytest
  pytest-sugar
commands_pre =
  pip install src/core src/authentication src/build src/log src/permissions src/settings src/web
# --import-mode=importlib is required to import all packages in namespace
# properly.
commands =
  pytest --import-mode=importlib {posargs}

# RFL depends on cached_property backport package on python < 3.8.

[testenv:py37]
deps =
  {[testenv]deps}
  cached_property
"""
